name: machine-learning-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - polars
  - pandas
  - jupyter
  - pyodbc
  - notebook
  - matplotlib
  - seaborn
  - scikit-learn
  - mne